spring:
  application:
    name: payment-api

server:
  port: 8081

app:
  version: ${APP_VERSION:2.0.0}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true

logging:
  structured:
    format:
      console: logstash
    json:
      stacktrace:
        max-throwable-depth: 12
        max-length: 3000
        include-common-frames: false
